# Generated by Django 5.1 on 2025-05-08 12:28

import apps.funcionarios.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_arquivofuncionario_arquivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arquivofuncionario',
            name='arquivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\vitor\\MoneyLink-Pro\\media\\arquivos_funcionarios'), upload_to=apps.funcionarios.models.get_funcionario_upload_path, verbose_name='Arquivo'),
        ),
    ]
