# Generated by Django 5.1 on 2025-05-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0008_alter_arquivofuncionario_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='ramal',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Ramal'),
        ),
    ]
