# Generated by Django 5.1 on 2025-05-22 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('funcionarios', '0011_alter_arquivofuncionario_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_pas', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.CreateModel(
            name='TipoPeriferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Tipo de Periférico',
                'verbose_name_plural': 'Tipos de Periféricos',
            },
        ),
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='computadores', to='funcionarios.loja')),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='Periferico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True)),
                ('data_aquisicao', models.DateField(blank=True, null=True)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perifericos', to='funcionarios.loja')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.tipoperiferico')),
            ],
            options={
                'verbose_name': 'Periférico',
                'verbose_name_plural': 'Periféricos',
            },
        ),
        migrations.CreateModel(
            name='PosicaoAtendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('manutencao', 'Em Manutenção'), ('inativa', 'Inativa')], default='livre', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario')),
                ('ilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_atendimento', to='ti.ilha')),
                ('sala', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ti.sala')),
            ],
            options={
                'verbose_name': 'Posição de Atendimento',
                'verbose_name_plural': 'Posições de Atendimento',
                'ordering': ['ilha', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoPerifericoPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField()),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('periferico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.periferico')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Periférico a PA',
                'verbose_name_plural': 'Atribuições de Periféricos a PAs',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoFuncionarioPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateField()),
                ('data_fim', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='funcionarios.funcionario')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Funcionário a PA',
                'verbose_name_plural': 'Atribuições de Funcionários a PAs',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoComputadorPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.computador')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
            ],
            options={
                'verbose_name': 'Atribuição de Computador a PA',
                'verbose_name_plural': 'Atribuições de Computadores a PAs',
            },
        ),
        migrations.AddField(
            model_name='ilha',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilhas', to='ti.sala'),
        ),
    ]
