# Generated by Django 5.1 on 2025-06-15 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0012_alter_arquivofuncionario_arquivo'),
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ilha',
            name='funcionario_responsavel',
        ),
        migrations.RemoveField(
            model_name='sala',
            name='funcionario_responsavel',
        ),
        migrations.AddField(
            model_name='chip',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chips_funcionario', to='funcionarios.funcionario', verbose_name='Funcionário'),
        ),
    ]
