# Generated by Django 5.1 on 2025-05-07 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0007_alter_arquivofuncionario_arquivo'),
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('quantidade_pas', models.PositiveIntegerField(default=1)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('andar', models.CharField(blank=True, max_length=20, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
            },
        ),
        migrations.AlterModelOptions(
            name='posicaoatendimento',
            options={'ordering': ['ilha', 'numero'], 'verbose_name': 'Posição de Atendimento', 'verbose_name_plural': 'Posições de Atendimento'},
        ),
        migrations.RemoveField(
            model_name='posicaoatendimento',
            name='localizacao',
        ),
        migrations.AddField(
            model_name='posicaoatendimento',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='funcionarios.funcionario'),
        ),
        migrations.AddField(
            model_name='posicaoatendimento',
            name='ilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posicoes_atendimento', to='ti.ilha'),
        ),
        migrations.AddField(
            model_name='ilha',
            name='sala',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ilhas', to='ti.sala'),
        ),
        migrations.AddField(
            model_name='posicaoatendimento',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ti.sala'),
        ),
    ]
