# Generated by Django 5.1 on 2025-06-03 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_arquivofuncionario_arquivo'),
        ('ti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimaAtualizacaoEstoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField()),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ultima_atualizacao_estoque', to='funcionarios.loja')),
            ],
            options={
                'verbose_name': 'Última Atualização de Estoque',
                'verbose_name_plural': 'Últimas Atualizações de Estoque',
            },
        ),
    ]
