# Generated by Django 5.1 on 2025-06-16 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_alter_arquivofuncionario_arquivo'),
        ('ti', '0002_remove_ilha_funcionario_responsavel_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acesso', models.CharField(max_length=255, verbose_name='Acesso')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sistema_acessos', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('ilha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ti.ilha', verbose_name='Ilha')),
            ],
            options={
                'verbose_name': 'Sistema - Acesso',
                'verbose_name_plural': 'Sistema - Acessos',
                'ordering': ['funcionario__nome_completo'],
                'unique_together': {('funcionario', 'acesso')},
            },
        ),
        migrations.CreateModel(
            name='Storm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('email_administrativo', models.EmailField(max_length=254, verbose_name='E-mail administrativo')),
                ('situacao', models.CharField(choices=[('ativo', 'Ativo'), ('desativado', 'Desativado')], default='ativo', max_length=20, verbose_name='Situação')),
                ('usuario', models.CharField(help_text='Máximo 4 números', max_length=4, verbose_name='Usuário (max 4 números)')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storm_acessos', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('sala_loja', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ti.sala', verbose_name='Sala/Loja')),
            ],
            options={
                'verbose_name': 'Storm - Acesso',
                'verbose_name_plural': 'Storm - Acessos',
                'ordering': ['funcionario__nome_completo'],
                'unique_together': {('funcionario', 'usuario')},
            },
        ),
    ]
