# Generated by Django 5.1 on 2025-05-08 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0002_ilha_sala_alter_posicaoatendimento_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sala',
            name='andar',
        ),
    ]
