# Generated by Django 5.1 on 2025-06-04 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0002_ultimaatualizacaoestoque'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atribuicaocomputadorpa',
            options={'verbose_name': 'Atribuição de Computador', 'verbose_name_plural': 'Computadores - Atribuições'},
        ),
        migrations.AlterModelOptions(
            name='atribuicaofuncionariopa',
            options={'verbose_name': 'Atribuição de Funcionário', 'verbose_name_plural': 'PAs - Atribuições de Funcionários'},
        ),
        migrations.AlterModelOptions(
            name='atribuicaoperifericopa',
            options={'verbose_name': 'Atribuição de Periférico', 'verbose_name_plural': 'Periféricos - Atribuições'},
        ),
        migrations.AlterModelOptions(
            name='posicaoatendimento',
            options={'ordering': ['ilha', 'numero'], 'verbose_name': 'PA', 'verbose_name_plural': 'PAs'},
        ),
        migrations.AlterModelOptions(
            name='tipoperiferico',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Periféricos - Tipos'},
        ),
        migrations.DeleteModel(
            name='UltimaAtualizacaoEstoque',
        ),
    ]
