# Generated by Django 5.1 on 2025-05-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0003_remove_sala_andar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuicaoperifericopa',
            name='data_atribuicao',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='atribuicaoperifericopa',
            name='data_remocao',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
