# Generated by Django 5.1 on 2025-06-04 14:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_arquivofuncionario_arquivo'),
        ('ti', '0003_alter_atribuicaocomputadorpa_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='loja',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas', to='funcionarios.loja'),
        ),
    ]
