# Generated by Django 5.1 on 2025-06-16 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0003_sistema_storm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storm',
            name='cpf',
        ),
    ]
