# Generated by Django 5.1 on 2025-06-05 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0004_sala_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posicaoatendimento',
            name='funcionario',
        ),
    ]
