# Generated by Django 5.1 on 2025-06-16 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0004_remove_cpf_from_storm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sistema',
            name='ilha',
        ),
        migrations.RemoveField(
            model_name='storm',
            name='sala_loja',
        ),
    ]
