# Generated by Django 5.1 on 2025-05-15 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0004_alter_atribuicaoperifericopa_data_atribuicao_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Computador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Computador',
                'verbose_name_plural': 'Computadores',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoComputadorPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True)),
                ('data_remocao', models.DateTimeField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
                ('computador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.computador')),
            ],
            options={
                'verbose_name': 'Atribuição de Computador a PA',
                'verbose_name_plural': 'Atribuições de Computadores a PAs',
            },
        ),
    ]
