# Generated by Django 5.1 on 2025-06-05 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0011_alter_arquivofuncionario_arquivo'),
        ('ti', '0005_remove_funcionario_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='condicao',
            field=models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição'),
        ),
        migrations.AddField(
            model_name='computador',
            name='estado',
            field=models.CharField(choices=[('funcionando', 'Funcionando'), ('com_defeito', 'Com Defeito'), ('em_reparo', 'Em Reparo')], default='funcionando', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='computador',
            name='modelo',
            field=models.CharField(default='Não Informado', max_length=100, verbose_name='Modelo'),
        ),
        migrations.AddField(
            model_name='computador',
            name='numero_serie',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série'),
        ),
        migrations.AddField(
            model_name='ilha',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ilhas_responsavel', to='funcionarios.funcionario', verbose_name='Funcionário Responsável'),
        ),
        migrations.AddField(
            model_name='ilha',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='condicao',
            field=models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição'),
        ),
        migrations.AddField(
            model_name='periferico',
            name='estado',
            field=models.CharField(choices=[('funcionando', 'Funcionando'), ('com_defeito', 'Com Defeito'), ('em_reparo', 'Em Reparo')], default='funcionando', max_length=20, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='posicaoatendimento',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AddField(
            model_name='sala',
            name='funcionario_responsavel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salas_responsavel', to='funcionarios.funcionario', verbose_name='Funcionário Responsável'),
        ),
        migrations.AddField(
            model_name='sala',
            name='setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salas_ti', to='funcionarios.setor', verbose_name='Setor'),
        ),
        migrations.AddField(
            model_name='sala',
            name='titulo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='marca',
            field=models.CharField(max_length=100, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='computador',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='ilha',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='ilha',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='ilha',
            name='quantidade_pas',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade de PAs'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='status',
            field=models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='posicaoatendimento',
            name='numero',
            field=models.CharField(max_length=20, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='posicaoatendimento',
            name='observacoes',
            field=models.TextField(blank=True, null=True, verbose_name='Observações'),
        ),
        migrations.AlterField(
            model_name='posicaoatendimento',
            name='status',
            field=models.CharField(choices=[('livre', 'Livre'), ('ocupada', 'Ocupada'), ('manutencao', 'Em Manutenção'), ('inativa', 'Inativa')], default='livre', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='descricao',
            field=models.TextField(blank=True, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=100, verbose_name='Modelo')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Número de Série')),
                ('tamanho', models.CharField(blank=True, max_length=20, null=True, verbose_name='Tamanho')),
                ('resolucao', models.CharField(blank=True, max_length=50, null=True, verbose_name='Resolução')),
                ('condicao', models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição')),
                ('estado', models.CharField(choices=[('funcionando', 'Funcionando'), ('com_defeito', 'Com Defeito'), ('em_reparo', 'Em Reparo')], default='funcionando', max_length=20, verbose_name='Estado')),
                ('status', models.CharField(choices=[('disponivel', 'Disponível'), ('em_uso', 'Em Uso'), ('manutencao', 'Em Manutenção'), ('inativo', 'Inativo')], default='disponivel', max_length=20, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('data_aquisicao', models.DateField(blank=True, null=True, verbose_name='Data de Aquisição')),
                ('loja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitores', to='funcionarios.loja')),
            ],
            options={
                'verbose_name': 'Monitor',
                'verbose_name_plural': 'Monitores',
            },
        ),
        migrations.CreateModel(
            name='AtribuicaoMonitorPA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_atribuicao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Atribuição')),
                ('data_remocao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Remoção')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('posicao_atendimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.posicaoatendimento')),
                ('monitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ti.monitor')),
            ],
            options={
                'verbose_name': 'Atribuição de Monitor',
                'verbose_name_plural': 'Monitores - Atribuições',
            },
        ),
    ]
