# Generated by Django 5.1 on 2025-05-15 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0005_computador_atribuicaocomputadorpa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='modelo',
        ),
    ]
