# Generated by Django 5.1 on 2025-06-20 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0013_alter_arquivofuncionario_arquivo'),
        ('ti', '0005_remove_sistema_ilha_remove_storm_sala_loja'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoordenadorSala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('coordenador', 'Coordenador'), ('supervisor', 'Supervisor Geral')], default='coordenador', max_length=20, verbose_name='Tipo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='Data de Fim')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenacao_salas', to='funcionarios.funcionario', verbose_name='Funcionário')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordenadores', to='ti.sala', verbose_name='Sala')),
            ],
            options={
                'verbose_name': 'Coordenador/Supervisor de Sala',
                'verbose_name_plural': 'Coordenadores/Supervisores de Salas',
                'ordering': ['sala__nome', 'funcionario__nome_completo'],
                'unique_together': {('funcionario', 'sala', 'tipo')},
            },
        ),
    ]
