# Generated by Django 5.1 on 2025-06-20 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0006_coordenadorsala'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordenadorsala',
            name='data_inicio',
        ),
        migrations.RemoveField(
            model_name='coordenadorsala',
            name='observacoes',
        ),
    ]
