# Generated by Django 5.1 on 2025-05-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0006_remove_computador_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='periferico',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
