# Generated by Django 5.1 on 2025-06-20 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0007_remove_coordenadorsala_data_inicio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='condicao',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='computador',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='data_aquisicao',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='modelo',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='numero_serie',
        ),
        migrations.RemoveField(
            model_name='monitor',
            name='resolucao',
        ),
    ]
