# Generated by Django 5.1 on 2025-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0008_remove_computador_condicao_remove_computador_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='computador',
            name='condicao',
            field=models.CharField(choices=[('novo', 'Novo'), ('antigo', 'Antigo')], default='novo', max_length=20, verbose_name='Condição'),
        ),
    ]
