# Generated by Django 5.1 on 2025-05-20 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0008_periferico_loja'),
    ]

    operations = [
        migrations.AddField(
            model_name='periferico',
            name='loja',
            field=models.CharField(choices=[('sede', 'Sede'), ('cachoeirinha', 'Cachoeirinha'), ('sao_leopoldo', 'São Leopoldo'), ('santa_maria', 'Santa Maria')], default='sede', max_length=20, verbose_name='Loja'),
        ),
    ]
