# Generated by Django 5.1 on 2025-05-20 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0010_computador_loja'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computador',
            name='loja',
            field=models.CharField(default='sede', max_length=50, verbose_name='Loja'),
        ),
        migrations.AlterField(
            model_name='periferico',
            name='loja',
            field=models.CharField(default='sede', max_length=50, verbose_name='Loja'),
        ),
    ]
