# Generated by Django 5.1 on 2025-05-21 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ti', '0011_alter_computador_loja_alter_periferico_loja'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='computador',
            name='loja',
        ),
        migrations.RemoveField(
            model_name='periferico',
            name='loja',
        ),
    ]
